// var nodemailer = require('nodemailer');
import nodemailer from "nodemailer";


var transport = nodemailer.createTransport({
  host: "smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: "2e3560b46bf83d", //example of generated by Mailtrap 
    pass: "5a2061f4cba1ba" //example of generated by Mailtrap 
  }
});
 
var mailOptions = {
  from: 'fazrinursyam@gmail.com',
  to: 'fazri18052002@gmail.com',
  subject: 'Test Nodemailer with Mailtrap',
  
  html: '<h1><button> Verivikasi! </button></h1>',
  attachments: [
    {   // utf-8 string as an attachment
        filename: 'text.txt',
        content: 'Attachments'
    }
  ]
};
 
export const emaill = transport.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.log(error);
  }
  console.log('Email sent: ' + info.response);
});